# format = "[ï®‚ ](cyan)$directory$character$git_branch$git_commit$git_status$character"
# format="$all"
# Don't print a new line at the start of the prompt
add_newline = false

[line_break]
disabled = true

# Hide the username. The username will only show in certain scenarios
[username]
disabled = true

# shows the hostname on new lines
[hostname]
ssh_only = true
format = "ğŸ’»ï¸[$hostname](bold italic #87A752)"
# suffix = ">>"
trim_at = ".companyname.com"
disabled = false

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
# success_symbol = "[âœ](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
# format = "[$character](bold)"
success_symbol = "[ï”](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "[ï”](bold red)"

[jobs]
threshold = 1
symbol = "âœ¦"
style = "bold blue"


# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
